<?php
require_once __DIR__ . '/../../config/connection.php';
require_once __DIR__ . '/../model/logs_model.php';

if (!isset($_SESSION['user_id'])) {
    header("Location: index.php?page=landing_");
    exit();
}

$user_id  = $_SESSION['user_id'];
$username = $_SESSION['username'] ?? 'User';

$search = $_GET['search'] ?? '';
$date_from = $_GET['date_from'] ?? '';
$date_to = $_GET['date_to'] ?? '';
$action_type = $_GET['action_type'] ?? '';
$remarks_search = $_GET['remarks_search'] ?? '';

$from = null;
$to = null;

if ($date_from && $date_to) {
    $from = date('Y-m-d 00:00:00', strtotime($date_from));
    $to = date('Y-m-d 23:59:59', strtotime($date_to));
    if (strtotime($from) > strtotime($to)) {
        $temp = $from; $from = $to; $to = $temp;
    }
} elseif ($date_from) {
    $from = date('Y-m-d 00:00:00', strtotime($date_from));
} elseif ($date_to) {
    $to = date('Y-m-d 23:59:59', strtotime($date_to));
}

$logs = get_stock_logs_by_date($pdo, $from, $to, $search, $action_type, $remarks_search);

$logMessage = "Generated stock report"
            . ($search ? " | Search: {$search}" : "")
            . ($date_from ? " | From: {$date_from}" : "")
            . ($date_to ? " | To: {$date_to}" : "")
            . ($remarks_search ? " | Search: {$remarks_search}" : "")
            . ($action_type ? " | Action: {$action_type}" : "");

if (isset($_GET['log']) && $_GET['log'] == 1) {
    add_activity_log($pdo, $user_id, null, $logMessage);
}

function format_date($datetime) {
    return date('M d, Y H:i', strtotime($datetime));
}

$date_range_display = '';
if ($date_from && $date_to) {
    $date_from_display = date('M d, Y', strtotime($date_from));
    $date_to_display = date('M d, Y', strtotime($date_to));
    $date_range_display = ($date_from_display === $date_to_display)
        ? $date_from_display
        : "{$date_from_display} to {$date_to_display}";
} elseif ($date_from) {
    $date_range_display = "From " . date('M d, Y', strtotime($date_from));
} elseif ($date_to) {
    $date_range_display = "Up to " . date('M d, Y', strtotime($date_to));
} else {
    $date_range_display = 'All Dates';
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" href="assets/images/logo.png">
<title>Stock Logs Report</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
<style>
* { box-sizing: border-box; }
body { font-family: Arial, sans-serif; margin: 20px; background: #fff; }
h2, h4 { text-align: center; margin: 0; }
table { width: 100%; border-collapse: collapse; margin-top: 20px; }
th, td { border: 1px solid #000; padding: 6px 8px; text-align: left; font-size: 11px; }
th { background-color: #f2f2f2; }

#download-btn {
    display: block;
    margin: 0 auto 20px auto;
    padding: 12px 30px;
    background-color: #28a745;
    color: white;
    border: none;
    border-radius: 6px;
    font-size: 16px;
    cursor: pointer;
    font-weight: bold;
}
#download-btn:hover { background-color: #218838; }
#download-btn:disabled { background-color: #6c757d; cursor: not-allowed; }
</style>
</head>
<body>

<div style="text-align:center; margin-bottom: 10px;">
    <button id="download-btn" onclick="generatePDF()">⬇ Download PDF</button>
    <p style="font-size:12px; color:#666; margin:4px 0 0 0;">Tap the button above to save as PDF</p>
</div>

<div id="report-content">
    <h2>Inventory System</h2>
    <h4>Stock Logs Report</h4>
    <p style="text-align:center; font-size:13px;">
        <strong>Date Range:</strong> <?= $date_range_display ?><br>
        <strong>Generated by:</strong> <?= htmlspecialchars($username) ?><br>
        <strong>Generated on:</strong> <?= date('M d, Y H:i') ?><br>
        <?php if ($search): ?>
        <strong>Search:</strong> "<?= htmlspecialchars($search) ?>"<br>
        <?php endif; ?>
        <?php if ($remarks_search): ?>
        <strong>Remarks Search:</strong> "<?= htmlspecialchars($remarks_search) ?>"<br>
        <?php endif; ?>
        <?php if ($action_type): ?>
        <strong>Action Type:</strong> <?= htmlspecialchars($action_type === 'IN' ? 'Stock In' : 'Stock Out') ?><br>
        <?php endif; ?>
    </p>

    <table>
    <thead>
    <tr>
        <th>#</th>
        <th>Product</th>
        <th>Part Number</th>
        <th>Action</th>
        <th>Quantity</th>
        <th>Total Before</th>
        <th>Total After</th>
        <th>Remarks</th>
        <th>Date</th>
    </tr>
    </thead>
    <tbody>
    <?php if (!empty($logs)): ?>
        <?php foreach ($logs as $i => $log):
            $action = strtoupper(trim($log['action']));
            $quantity = (int)$log['quantity'];
        ?>
            <tr>
                <td><?= $i + 1 ?></td>
                <td><?= htmlspecialchars($log['product_name']) ?></td>
                <td><?= htmlspecialchars($log['part_number']) ?></td>
                <td>
                    <span style="color: <?= $action === 'IN' ? 'green' : 'red' ?>; font-weight: bold;">
                        <?= $action === 'IN' ? 'Stock In' : 'Stock Out' ?>
                    </span>
                </td>
                <td style="text-align: center; color: <?= $action === 'IN' ? 'green' : 'red' ?>; font-weight: bold;">
                    <?= $action === 'IN' ? '+' : '-' ?><?= abs($quantity) ?>
                </td>
                <td style="text-align: center;"><?= htmlspecialchars($log['balance_before']) ?></td>
                <td style="text-align: center;"><?= htmlspecialchars($log['balance_after']) ?></td>
                <td><?= htmlspecialchars($log['remarks'] ?? '-') ?></td>
                <td><?= format_date($log['created_at']) ?></td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="9" style="text-align:center; padding: 40px; color: #666; font-style: italic;">
                No stock logs found for the selected criteria.
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
    </table>
</div>

<script>
function generatePDF() {
    const btn = document.getElementById('download-btn');
    btn.disabled = true;
    btn.textContent = 'Generating PDF...';

    const element = document.getElementById('report-content');
    const filename = 'stock_logs_<?= date('Ymd_Hi') ?>.pdf';

    const opt = {
        margin:       [10, 8, 10, 8],
        filename:     filename,
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2, useCORS: true, logging: false },
        jsPDF:        { unit: 'mm', format: 'a4', orientation: 'landscape' },
        pagebreak:    { mode: ['avoid-all', 'css', 'legacy'] }
    };

    html2pdf().set(opt).from(element).save().then(function() {
        btn.disabled = false;
        btn.textContent = '⬇ Download PDF';
    }).catch(function(err) {
        console.error('PDF error:', err);
        btn.disabled = false;
        btn.textContent = '⬇ Download PDF';
        alert('PDF generation failed. Please try again.');
    });
}

// Auto-trigger on page load
window.addEventListener('load', function() {
    setTimeout(generatePDF, 800);
});
</script>

</body>
</html>