<?php
require_once __DIR__ . '/../../config/connection.php';
require_once __DIR__ . '/../model/logs_model.php';
if (!isset($_SESSION['user_id'])) {
    header("Location: index.php?page=landing_page");
    exit();
}
$username = $_SESSION['username'] ?? 'User';
$user_id  = $_SESSION['user_id'];
$search = trim($_GET['search'] ?? '');
$date_from = trim($_GET['date_from'] ?? '');
$date_to = trim($_GET['date_to'] ?? '');
if ($date_from && $date_to) {
    $from = date('Y-m-d 00:00:00', strtotime($date_from));
    $to   = date('Y-m-d 23:59:59', strtotime($date_to));
} else {
    $from = null;
    $to   = null;
}
$logs = get_activity_logs_by_date($pdo, $from, $to, $search);
function format_date($datetime) {
    return date('M d, Y H:i', strtotime($datetime));
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" href="assets/images/logo.png">
<title>Activity Logs Report</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
<style>
* { box-sizing: border-box; }
body { font-family: Arial, sans-serif; margin: 20px; background: #fff; }
h2, h4 { text-align: center; margin: 0; }
table { width: 100%; border-collapse: collapse; margin-top: 20px; }
th, td { border: 1px solid #000; padding: 6px 8px; text-align: left; font-size: 12px; }
th { background-color: #f2f2f2; }

#download-btn {
    display: block;
    margin: 0 auto 20px auto;
    padding: 12px 30px;
    background-color: #28a745;
    color: white;
    border: none;
    border-radius: 6px;
    font-size: 16px;
    cursor: pointer;
    font-weight: bold;
}
#download-btn:hover { background-color: #218838; }
#download-btn:disabled { background-color: #6c757d; cursor: not-allowed; }
</style>
</head>
<body>

<div class="no-print" style="text-align:center; margin-bottom: 10px;">
    <button id="download-btn" onclick="generatePDF()">⬇ Download PDF</button>
    <p style="font-size:12px; color:#666; margin:4px 0 0 0;">Tap the button above to save as PDF</p>
</div>

<div id="report-content">
    <h2>Inventory System</h2>
    <h4>Activity Logs Report</h4>
    <p style="text-align:center; font-size:13px;">
        Date Range: <?= $date_from ? date('M d, Y', strtotime($date_from)) : 'All' ?>
        - <?= $date_to ? date('M d, Y', strtotime($date_to)) : 'All' ?><br>
        Generated by: <?= htmlspecialchars($username) ?><br>
        Generated on: <?= date('M d, Y H:i') ?>
    </p>

    <table>
    <thead>
    <tr>
        <th>#</th>
        <th>Activity</th>
        <th>Date</th>
    </tr>
    </thead>
    <tbody>
    <?php if (!empty($logs)): ?>
        <?php foreach ($logs as $i => $log): ?>
            <tr>
                <td><?= $i + 1 ?></td>
                <td><?= htmlspecialchars($log['activity']) ?></td>
                <td><?= format_date($log['created_at']) ?></td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="3" style="text-align:center;">No records found for the selected date range.</td>
        </tr>
    <?php endif; ?>
    </tbody>
    </table>
</div>

<script>
function generatePDF() {
    const btn = document.getElementById('download-btn');
    btn.disabled = true;
    btn.textContent = 'Generating PDF...';

    const element = document.getElementById('report-content');
    const filename = 'activity_logs_<?= date('Ymd_Hi') ?>.pdf';

    const opt = {
        margin:       [10, 8, 10, 8],
        filename:     filename,
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2, useCORS: true, logging: false },
        jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak:    { mode: ['avoid-all', 'css', 'legacy'] }
    };

    html2pdf().set(opt).from(element).save().then(function() {
        btn.disabled = false;
        btn.textContent = '⬇ Download PDF';
    }).catch(function(err) {
        console.error('PDF error:', err);
        btn.disabled = false;
        btn.textContent = '⬇ Download PDF';
        alert('PDF generation failed. Please try again.');
    });
}

// Auto-trigger on page load
window.addEventListener('load', function() {
    setTimeout(generatePDF, 800);
});
</script>

</body>
</html>