<?php
require_once __DIR__ . '/../../config/connection.php';
require_once __DIR__ . '/../model/manage_products_model.php';
require_once __DIR__ . '/../model/logs_model.php';

if (!isset($_SESSION['user_id'])) {
    header("Location: index.php?page=landing_page");
    exit();
}

$username = $_SESSION['username'] ?? 'User';
$user_id  = $_SESSION['user_id'];
// Get filter parameters from URL
$category_id = isset($_GET['category_id']) ? intval($_GET['category_id']) : null;
$category_name = isset($_GET['category_name']) ? htmlspecialchars($_GET['category_name']) : 'All Categories';
$search_term = isset($_GET['search']) ? htmlspecialchars($_GET['search']) : '';
$logMessage = "Generated inventory report";

if ($category_name && $category_name !== 'All Categories') {
    $logMessage .= " | Category: {$category_name}";
}

if (!empty($search_term)) {
    $logMessage .= " | Search: {$search_term}";
}
$logKey = 'inventory_report_logged_' . md5($logMessage);

if (isset($_GET['log']) && $_GET['log'] == 1 && empty($_SESSION[$logKey])) {
    add_activity_log($pdo, $user_id, null, $logMessage);
    $_SESSION[$logKey] = true;
}
    

// Build query with filters
$query = "SELECT p.*, c.category_name 
          FROM products p
          LEFT JOIN categories c ON p.category_id = c.id
          WHERE p.is_deleted = 0";
          
$params = [];

if ($category_id) {
    $query .= " AND p.category_id = ?";
    $params[] = $category_id;
}

if (!empty($search_term)) {
    $query .= " AND (p.product_name LIKE ? 
                    OR p.sku LIKE ? 
                    OR p.part_number LIKE ? 
                    OR p.applicable_models LIKE ?)";
    $search_param = "%{$search_term}%";
    array_push($params, $search_param, $search_param, $search_param, $search_param);
}

$query .= " ORDER BY c.category_name, p.product_name";

$stmt = $pdo->prepare($query);
$stmt->execute($params);
$products = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Get ALL products for category totals (when not filtered by category)
$all_products_query = "SELECT p.*, c.category_name 
                       FROM products p
                       LEFT JOIN categories c ON p.category_id = c.id
                       WHERE p.is_deleted = 0
                       ORDER BY c.category_name";
$all_products_stmt = $pdo->prepare($all_products_query);
$all_products_stmt->execute();
$all_products = $all_products_stmt->fetchAll(PDO::FETCH_ASSOC);

function format_currency($amount) {
    return '₱' . number_format($amount, 2);
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" href="assets/images/logo.png">
<title>Inventory Report</title>
<!-- html2pdf.js for mobile-compatible PDF export -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
<style>
* { box-sizing: border-box; }
body { font-family: Arial, sans-serif; margin: 20px; background: #fff; }
h2, h4 { text-align: center; margin: 0; }
table { width: 100%; border-collapse: collapse; margin-top: 20px; }
th, td { border: 1px solid #000; padding: 6px 8px; text-align: left; font-size: 12px; }
th { background-color: #f2f2f2; }
.low-stock { background-color: #fff3cd; }
.out-stock { background-color: #f8d7da; }
.category-header { background-color: #e9ecef !important; font-weight: bold; }
.total-row { background-color: #f8f9fa !important; font-weight: bold; border-top: 2px solid #000; }
.grand-total { background-color: #d4edda !important; font-weight: bold; border-top: 2px solid #000; }

/* Download button - hidden when generating PDF */
#download-btn {
    display: block;
    margin: 0 auto 20px auto;
    padding: 12px 30px;
    background-color: #28a745;
    color: white;
    border: none;
    border-radius: 6px;
    font-size: 16px;
    cursor: pointer;
    font-weight: bold;
}
#download-btn:hover { background-color: #218838; }
#download-btn:disabled { background-color: #6c757d; cursor: not-allowed; }

.no-print { }
@media print {
    .no-print { display: none !important; }
}
</style>
</head>
<body>

<!-- Download Button (visible on all devices) -->
<div class="no-print" style="text-align:center; margin-bottom: 10px;">
    <button id="download-btn" onclick="generatePDF()">⬇ Download PDF</button>
    <p style="font-size:12px; color:#666; margin:4px 0 0 0;">Tap the button above to save as PDF</p>
</div>

<!-- Report Content -->
<div id="report-content">
    <h2>Grease Monkey Inventory System</h2>
    <h4>Products Report</h4>
    <p style="text-align:center; font-size:13px;">
        Category: <?= $category_name ?><br>
        <?php if (!empty($search_term)): ?>
            Search: "<?= $search_term ?>"<br>
        <?php endif; ?>
        Generated by: <?= htmlspecialchars($username) ?><br>
        Generated on: <?= date('M d, Y H:i') ?>
    </p>

    <?php if (!empty($products)): ?>
        <?php
        $total_products = count($products);
        $total_stock = 0;
        $total_value = 0;
        
        $category_totals = [];
        $display_products = $category_id ? $products : $all_products;
        
        foreach ($display_products as $p) {
            $cat_name = $p['category_name'] ?? 'Uncategorized';
            if (!isset($category_totals[$cat_name])) {
                $category_totals[$cat_name] = ['count' => 0, 'stock' => 0, 'value' => 0];
            }
            $category_totals[$cat_name]['count']++;
            $category_totals[$cat_name]['stock'] += $p['stock'];
            $category_totals[$cat_name]['value'] += ($p['stock'] * $p['price']);
        }
        
        foreach ($products as $p) {
            $total_stock += $p['stock'];
            $total_value += ($p['stock'] * $p['price']);
        }
        ?>
        
        <p style="text-align:center; font-weight:bold; font-size:13px;">
            Total Products: <?= $total_products ?> |
            Total Stock: <?= $total_stock ?> units |
            Total Value: <?= format_currency($total_value) ?>
        </p>
        
        <table>
        <thead>
        <tr>
        <th>#</th>
        <th>Product</th>
        <th>SKU</th>
        <th>Part Number</th>
        <th>Category</th>
        <th>Stock</th>
        <th>Price</th>
        <th>Total Value</th>
        </tr>
        </thead>
        <tbody>
        <?php 
        $counter = 1;
        $current_category = null;
        
        foreach ($products as $p): 
            $cat_name = $p['category_name'] ?? 'Uncategorized';
            
            if ($current_category !== $cat_name) {
                $current_category = $cat_name;
                ?>
                <tr class="category-header">
                    <td colspan="8">Category: <?= htmlspecialchars($cat_name) ?></td>
                </tr>
                <?php
            }
            
            $class = '';
            if ($p['stock'] == 0) {
                $class = 'out-stock';
            } elseif ($p['stock'] < 10) {
                $class = 'low-stock';
            }
            ?>
            <tr class="<?= $class ?>">
                <td><?= $counter++ ?></td>
                <td><?= htmlspecialchars($p['product_name']) ?></td>
                <td><?= htmlspecialchars($p['sku']) ?></td>
                <td><?= htmlspecialchars($p['part_number'] ?? '-') ?></td>
                <td><?= htmlspecialchars($cat_name) ?></td>
                <td><?= $p['stock'] ?></td>
                <td><?= format_currency($p['price']) ?></td>
                <td><?= format_currency($p['stock'] * $p['price']) ?></td>
            </tr>
        <?php endforeach; ?>
        
        <tr class="total-row">
            <td colspan="5" style="text-align:right;">Filtered Products Total:</td>
            <td><?= $total_stock ?></td>
            <td></td>
            <td><?= format_currency($total_value) ?></td>
        </tr>
        
        </tbody>
        </table>
        
        <?php if (!$category_id): ?>
            <h4 style="margin-top: 30px;">Category Summary</h4>
            <table style="margin-top: 10px;">
            <thead>
            <tr>
            <th>Category</th>
            <th>Products</th>
            <th>Total Stock</th>
            <th>Total Value</th>
            </tr>
            </thead>
            <tbody>
            <?php 
            $grand_total_count = 0;
            $grand_total_stock = 0;
            $grand_total_value = 0;
            
            foreach ($category_totals as $cat_name => $totals): 
                $grand_total_count += $totals['count'];
                $grand_total_stock += $totals['stock'];
                $grand_total_value += $totals['value'];
            ?>
            <tr>
                <td><?= htmlspecialchars($cat_name) ?></td>
                <td><?= $totals['count'] ?></td>
                <td><?= $totals['stock'] ?></td>
                <td><?= format_currency($totals['value']) ?></td>
            </tr>
            <?php endforeach; ?>
            
            <tr class="grand-total">
                <td><strong>GRAND TOTAL</strong></td>
                <td><?= $grand_total_count ?></td>
                <td><?= $grand_total_stock ?></td>
                <td><?= format_currency($grand_total_value) ?></td>
            </tr>
            </tbody>
            </table>
        <?php endif; ?>
        
    <?php else: ?>
        <table>
        <tbody>
        <tr>
            <td colspan="8" style="text-align:center; padding: 20px;">No products found matching your filters.</td>
        </tr>
        </tbody>
        </table>
    <?php endif; ?>
</div>

<script>
function generatePDF() {
    const btn = document.getElementById('download-btn');
    btn.disabled = true;
    btn.textContent = 'Generating PDF...';

    const element = document.getElementById('report-content');
    const filename = 'inventory_report_<?= date('Ymd_Hi') ?>.pdf';

    const opt = {
        margin:       [10, 8, 10, 8], // top, left, bottom, right in mm
        filename:     filename,
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2, useCORS: true, logging: false },
        jsPDF:        { unit: 'mm', format: 'a4', orientation: 'landscape' },
        pagebreak:    { mode: ['avoid-all', 'css', 'legacy'] }
    };

    html2pdf().set(opt).from(element).save().then(function() {
        btn.disabled = false;
        btn.textContent = '⬇ Download PDF';
    }).catch(function(err) {
        console.error('PDF error:', err);
        btn.disabled = false;
        btn.textContent = '⬇ Download PDF';
        alert('PDF generation failed. Please try again.');
    });
}

// Auto-generate on page load (mirrors original behavior)
window.addEventListener('load', function() {
    // Short delay to ensure page is fully rendered
    setTimeout(generatePDF, 800);
});
</script>

</body>
</html>